apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets-test-kv-camelcase
  namespace: backstage
spec:
  dataFrom:
    - extract:
        key: 17794b6b-76f9-45a5-dbbe-b863c0b81801
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner

