apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  dataFrom:
    - extract:
        key: 26db169d-c4b4-dd6b-9135-77d8a7de095f
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner

