apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets-test-arbi-kv
  namespace: backstage
spec:
  dataFrom:
    - extract:
        key: 095a65c5-771a-2668-9f6e-86227a2c9b10
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner

