apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  dataFrom:
    - extract:
        key: e3be0f3e-bf38-edba-0940-1e2271262c55
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner
    template:
      # this template is added for the sake of clarity
      # even without template, all keys in dataFrom.extract.key will be loaded automatically
      type: Opaque
      data:
        AUTH_GITHUB_CLIENT_ID: "{{ .AUTH_GITHUB_CLIENT_ID }}"
        AUTH_GITHUB_CLIENT_SECRET: "{{ .AUTH_GITHUB_CLIENT_SECRET }}"
        GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"

