apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secrets
  namespace: backstage
spec:
  data:
    - secretKey: postgresqlDatabase
      remoteRef:
        key: 854ad7ac-8067-af4c-6ab6-bd6506859039
    - secretKey: postgresqlPassword
      remoteRef:
        key: 23e23248-db9d-420b-89db-b284dd735bb4
    - secretKey: postgresqlAdminPassword
      remoteRef:
        key: d3bc7c48-6352-5d56-1818-7a43d8b5a1c2
    - secretKey: postgresqlUser
      remoteRef:
        key: 0d85212e-dc36-50d5-5a62-ee09192d1bc6
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: postgresql-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        POSTGRESQL_DATABASE: |-
          {{ .postgresqlDatabase | toString }}
        POSTGRESQL_PASSWORD: |-
          {{ .postgresqlPassword | toString }}
        POSTGRESQL_ADMIN_PASSWORD: |-
          {{ .postgresqlAdminPassword | toString }}
        POSTGRESQL_USER: |-
          {{ .postgresqlUser | toString }}
