apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secrets
  namespace: backstage
spec:
  dataFrom:
    - extract:
        key: 705d8a8b-862d-1e18-ef9f-fbc9fc401f87
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: postgresql-secrets
    creationPolicy: Owner

