apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secrets
  namespace: backstage
spec:
  dataFrom:
    - extract:
        key: 5edfefa4-28b0-f228-e7bd-00a1545072bc
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: postgresql-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        test: |-
          {{ .data.POSTGRESQL_DATABASE | toString }}
