kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: upbound-system

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: universal-crossplane
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'