kind: Deployment
apiVersion: apps/v1
metadata:
  name: backstage
  namespace: backstage
  labels:
    app.kubernetes.io/instance: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      volumes:
        - name: app-config
          configMap:
            name: app-config
            defaultMode: 420
      containers:
        - name: backstage
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          ports:
            - name: http
              containerPort: 7007
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: app-config
              mountPath: /otp/app-config.yaml
              subPath: app-config.yaml
          envFrom:
            - configMapRef:
                name: backstage-cm
            - secretRef:
                name: postgresql-secrets
            - secretRef:
                name: backstage-secrets-kube
          image: image-registry.openshift-image-registry.svc:5000/openshift/nodejs:latest