 kind: RoleBinding
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: anyuid-rolebinding
 subjects:
   - kind: ServiceAccount
     name: crossplane
   - kind: ServiceAccount
     name: rbac-manager
 roleRef:
   kind: Role
   name: anyuid-role
   apiGroup: rbac.authorization.k8s.io