apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git-cli.yaml
  - git-clone.yaml
  # - https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.5/git-clone.yaml   (Does not work => Malformed URL)
  # - https://github.com/tektoncd/catalog/blob/main/task/git-cli/0.4/git-cli.yaml       (Same as above)