apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: provider-aws
  namespace: crossplane-system
spec:
  data:
    - secretKey: AWSProvider
      remoteRef:
        key: df5b0bc6-eefb-7fa1-99f7-dea1dab1cf77
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: AWSProvider
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        AWSProvider: |-
          {{ .AWSProvider | toString }}