apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

resources:
  - https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.5/git-clone.yaml
  - https://github.com/tektoncd/catalog/blob/main/task/git-cli/0.4/git-cli.yaml