kind: Deployment
apiVersion: apps/v1
metadata:
  name: backstage
  namespace: backstage-dev
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"backstage:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"backstage\")].image"}]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      volumes:
        - name: app-config
          configMap:
            name: app-config
            defaultMode: 420
      containers:
        - name: backstage
          ports:
            - name: http
              containerPort: 7007
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: app-config
              mountPath: /config/app-config.yaml
              subPath: app-config.yaml
          terminationMessagePolicy: File
          envFrom:
            - secretRef:
                name: postgresql-secrets
            - secretRef:
                name: backstage-secrets-kube
          image: >-
            image-registry.openshift-image-registry.svc:5000/backstage-dev/backstage:latest
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600