apiVersion: v2
name: crossplane
description: A Helm chart for Crossplane
type: application
version: 1.10.1
appVersion: 1.10.1
dependencies:
  - name: crossplane
    version: 1.10.1
    repository: https://charts.crossplane.io/stable