apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configure-provider-deployment-role-binding
  namespace: crossplane-system
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: tekton
roleRef:
  kind: ClusterRole
  name: tekton-pipeline-role
  apiGroup: rbac.authorization.k8s.io
