apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: secrets-manager
            namespace: external-secrets
            key: apiKey
      serviceUrl: >-
        https://9227c6a6-4665-4f4f-8d6e-ef7096f3b010.us-south.secrets-manager.appdomain.cloud
