# Generate this file with sealed-secret.sh
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets-manager
  namespace: external-secrets
spec:
  encryptedData:
    apiKey: AgAJHgd01GymwQ0MBwia2IC71Gn8G35aLVQ4kpI2Roh6K4ddH3672ueALoHgRgCZXeonHhbVaGIjXKNt6DQQJjYB2OLB06rbtFtppLceddYiF/VJ1Tns8VFKUUCCwHFBmcJAN6mUwHFJvP/3OzsllVr0uaZLi1nKbfYZo+glvDURtqYxmxbDCHM/yZZRjg9kEt36xWghe7vKQGwkilPkyN/rQgfjv5tW1RxsXYYMQFhexJKLazc56KNMUaVqPHFyu7STg65NfroA5Uy+sK73OaKFoRJ1iGiUy77NOtoHS5gp7NddZqXMerNy0gDqmoLYSBGE37hVu/egQVsh6b+8SnxFeMXcED4Z6/sRXIfnrWWfYO2Ot6rl4+Z09oG9Bo8GCOMLXVgpcnJLKS4LVCbMdXO3EcL60CPpQTYSP0c5caCq41mwLRb8yYODnT88zjrtCSBed6j/GOtq1tqw1A6ont9uDWHLvnN64tmf2BnPqdIb2jEuemnV1jMiiH0SrE2i+5YXfb+HSrq4e+29Ndw8qNVcl7v/IPRAvorwoWbRgGlZZJGdyt/dBq5cdxB1nVmmBjYxrSjladm1AqH5peg/UqOxwxX2Kfr8dSgUpzh/DTi00ez0qsUQW9Os6gB2dq8xwpRGRAQtTY4cA6vj6m6BUtAHL8o4EnvC0n4REF2FrUDsrRSMNcBve0keeJJCZdOhL8pe/Z/uxSqxvNShk2l9Pt2T41kh6atorxW5K3if2gPVC5VtgH2flJ1jX6saAg==
  template:
    metadata:
      creationTimestamp: null
      name: secrets-manager
      namespace: external-secrets

