kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: crossplane-system

bases:
  - ../../base

patches:
  - target:
      kind: Provider
      name: provider-aws
    patch: |-
      - op: replace
        path: /spec/package
        value: 'crossplane/provider-aws:v0.37.1'