apiVersion: batch/v1
kind: Job
metadata:
  name: provider-ibm-cloud-configuration
  namespace: crossplane-system
spec:
  template:
    spec:
      serviceAccountName: configure-provider-deployment-sa
      containers:
      - name: provider-configuration
        image: quay.io/langley_millard_ibm/ibm-cloud-provider-config-job
        command: ["./configure-deployment.sh"]
        env:
        - name: KUBECONFIG
          value: "/tmp/config"
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 2
