apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: provider-aws
  namespace: crossplane-system
spec: 
  data:
  - secretKey: provideraws
    remoteRef: 
      key: a73c11b3-bd7d-27b9-9449-27a3ed37e214
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: cluster
    kind: ClusterSecretStore
  target:
    name: provider-aws
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        creds: |-
          {{ .provideraws | toString }}