kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: cluster-crud
  namespace: tekton
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: cluster-crud
spec:
  to:
    kind: Service
    name: el-cluster-crud
  tls: null
  port:
    targetPort: http-listener
