apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-tf
  namespace: crossplane-system
spec:
  package: "crossplane/provider-terraform:v0.3.0"
  controllerConfigRef:
    name: terraform-config