kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: crossplane-system

bases:
  - ../../base

patches:
  - target:
      kind: Provider
      name: aws-provider-config
    patch: |-
      - op: replace
        path: /spec/credentials/secretRef/key
        value: 'creds'
      - op: replace
        path: /spec/credentials/secretRef/name
        value: 'aws-creds'
      