apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: provider-aws
  namespace: crossplane-system
spec: 
  data:
  - secretKey: provideraws
    remoteRef: 
      key: 6d687600-1ee9-0822-76a4-2297b8d29387
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: cluster
    kind: ClusterSecretStore
  target:
    name: provider-aws
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        creds: |-
          {{ .provideraws | toString }}