apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider-config
spec:
  credentials:
    secretRef:
      key: CHANGEME
      name: CHANGEME
      namespace: crossplane-system
    source: Secret

