apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: backstage-cr-integration-tt
  namespace: tekton
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: backstage-pipeline-run-
      spec:
        pipelineRef:
          name: clone
        podTemplate:
          securityContext:
            fsGroup: 65532
        serviceAccountName: pipeline
        params:
          - name: GIT_USER_EMAIL
            value: "backstage-bot@ibm.com"
          - name: GIT_USER_NAME
            value: "backstage-bot"
          - name: GIT_SCRIPT
            value: |
              echo "Not used"
          - name: branch-name
            value: main
          - name: GIT_TARGET_REPO
            value: 'git@github.com:ce-apac-project-idp/otp-gitops-apps.git'
          - name: targetEnv
            value: $(tt.params.targetEnv)
          - name: repo-url
            value: $(tt.params.git-url)
          - name: REQUESTOR_ID
            value: $(tt.params.developerName)
          - name: APPLICATION_NAME
            value: $(tt.params.applicationName)
        workspaces:
          - name: ssh-credentials
            secret:
              secretName: git-credentials
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi