apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: guestbook-deploy-
spec:
  pipelineRef:
    name: guestbook-deploy
  params:
    - name: cluster-name
      value: local-cluster
    - name: version
      value: v1
  serviceAccountName: pipeline
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: ocs-storagecluster-cephfs
    - name: ssh-credentials
      secret:
        secretName: git-cli-ssh-private-key
    - configMap:
        name: git-data
      name: git-configmap