apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets-manager
  namespace: backstage
spec:
  encryptedData:
    apiKey: AgBFSbTb7xHyJBY2wZX9ZSq5kf7xxE6Pdujge8iS1p5KdWG1tTitMbnu2V3RDr9WfTvG6xOBFIiBG6vPIUKHa5W52pbKjaruRJrfpHbqjBXvYpIaat0B7V1w/t4GV21pVbWMQuYd4HIN2fq9MoyBqtq2fKYJ58QVdviDu1Ad+6NO4f2V+E7qHerza5O++uT2BTtc+j0lnvoBbFdQcggzyXUq0kVjXFoMVZM4UnghoyfrkbOIlRN7sWwM6CAZxZVap2URM6C1o7G5Rjti57c0YCX15WQG5eQyb7hrookBYZT4IPkVm7iK9yGdm4I/hZrTzQ3nJJDl1GTue0Dhg7J+DhUEFi33kcTIfPXGUGAsngJRkclAQlJhH1p4oqg0bSAzaI8hPQpmkKeEJqpALCEshKHObSgGDe5RVuMAKs4jiBkJ1NyjIebzn8rc0R7F0Q0N2J/oGPpdpKhxFQvE6wd0dZfpoTgOA607UpHDHraJZIQOL2rvw6B5DZSntcuXzNv1pE0qSm7AIECsDjrNAlUfZs/38lLDVJtPTPddTMITeIUMXJk1Hx3ilwTXz2fsAtFUF8si3OXbu+idq11uJHKCHJ3KQebqaFtS5/xj++/Hi6rVMnrD4rf23j4PmZAca/AWcozL3joARx2XrQH0yAFss1j+Hei1H3J1RFWDQx92NIvSya6bEoWx04cgciSEJo7y0+Z9E3yxacrSNvjO1NDDwFUmoNrjJ+YQzsTG+y1nJPxMKYgKS11/NQC2SYrRRw==
  template:
    metadata:
      creationTimestamp: null
      name: secrets-manager
      namespace: backstage