apiVersion: resourcecontrollerv2.ibmcloud.crossplane.io/v1alpha1
kind: ResourceInstance
metadata:
  name: idp-crossplane-cos-instance-n7f543
spec:
  forProvider:
    name: idp-crossplane-cos-instance-n7f543
    target: global
    serviceName: cloud-object-storage
    resourcePlanName: standard
    tags:
      - dev
  providerConfigRef:
    name: ibm-cloud