apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-cli-ssh-private-key
  namespace: tekton
spec:
  data:
  - secretKey: gitCliPrivateKey
    remoteRef: 
      key: a272585d-a006-b080-2c31-1c4a4dc49c91
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: git-cli-ssh-private-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        id_rsa: |-
          {{ .gitCliPrivateKey | toString }}
  